version: "3"

services:
  expense-tracker:
    image: hz642/expense-tracker:latest
    volumes:
      - /home/hz642/expense_tracker.db:/usr/instance/expense_tracker.db
    ports:
      - "80:8000"
    env_file:
      - /api/.env